services:
  
  spark:
    image: docker.io/bitnami/spark:latest
    container_name: spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - type: bind
        source: ./data
        target: /app/data
      - type: bind
        source: ./scripts
        target: /app/scripts

    mem_limit: 4g
    cpus: 2
    